
# Server Configuration
spring.application.name=chatbot
server.port=8902
server.servlet.context-path=/chatbot

# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/smb_lending_chatbot
spring.datasource.username=root
spring.datasource.password=jdpg(Ei.D27,
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Meta WhatsApp Configuration
whatsapp.verify.token=smblendingchatbot
whatsapp.access.token=EAATFOitvCtwBP9ZCpxaZAL5ZBKx6OScfZCgTSd9ezuIfpFA60JY7a3bnmcLtxJ2FLvBZCpHkQJa5ARw7ka2mtWcapUGfi7xwcLPYZCc7bo25vzuOcUVZANJZAUNTIXpk8sui7UZAgwtUcHnoLsPZBRtHEGhQjLNdHc1uBKxyex1uvejt4ENyhWjbK5hAdRZCniZAZCBea2BMphrxnE4m01AREEXWzml8elaUPCZCg0iGFDkpHvDZCjgY5BwqjYgr8xk765JuEnVrGRxrcxRnok2DZAIdsmZAPngZDZD
whatsapp.phone.number.id=920962674428205
whatsapp.business.account.id=828006363312044
whatsapp.api.url=https://graph.facebook.com/v18.0



# SSL stuff
server.ssl.enabled=true
server.ssl.key-store=/home/ec2-user/ssl/springboot.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=springboot
 
# Optional: Force HTTPS
server.ssl.enabled-protocols=TLSv1.2,TLSv1.3
server.ssl.ciphers=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384


# Toqan AI Agent Configuration
toqan.api.base-url=https://api.coco.prod.toqan.ai
toqan.api.key=sk_2c6abb09ad70714ea4e3415159d0d51c95f2c58479f75626a8ff73014a26d7b04d8160862c41eaaaac473bef7f0aa5f52526608ea9a1bb075ea5d2249db7
toqan.api.timeout=30
toqan.polling.max-attempts=20
toqan.polling.interval-ms=2000

# Logging
logging.level.com.hackathon.lending=DEBUG
logging.level.org.springframework.web=INFO
logging.level.com.hackathon.lending.bot.aiagent=DEBUG
